### ISSUE TITLE
Current Date hover Text Color

### ISSUE THREAD

**Issue by RitvikSardana** [tomosterlund/qalendar-light-mode-test#1]
<img width="1290" alt="Screenshot 2023-12-06 at 1 01 59 PM" src="https://github.com/tomosterlund/qalendar-light-mode-test/assets/65544983/af8ee0c6-cbb3-4e5a-94dd-ebca9d9b90cf">

When the current Date is hovered, the font color should change to Black instead of white.
Currently it looks unreadable

**Comment by tomosterlund** [comment]
Hi @RitvikSardana. This is not the official repository for Qalendar. Feel free to re-open your issue in https://github.com/tomosterlund/qalendar
